---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /mutate-zy-tech-v1-aloys
    failurePolicy: Fail
    name: maloys.kb.io
    rules:
      - apiGroups:
          - zy.tech
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - aloys
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-zy-tech-v1-aloys
    failurePolicy: Fail
    name: valoys.kb.io
    rules:
      - apiGroups:
          - zy.tech
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - aloys
    sideEffects: None