# permissions for end users to edit aloys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aloys-editor-role
rules:
  - apiGroups:
      - zy.tech
    resources:
      - aloys
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - zy.tech
    resources:
      - aloys/status
    verbs:
      - get