# permissions for end users to view aloys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aloys-viewer-role
rules:
  - apiGroups:
      - zy.tech
    resources:
      - aloys
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - zy.tech
    resources:
      - aloys/status
    verbs:
      - get