#设置部署命名空间
namespace: aloys-system

#在资源前面添加前缀
namePrefix: aloys-system-

#修改的文件
resources:
  - zy_v1_aloys.yaml

#添加 labels
commonLabels:
  app: kustomize-nginx

#集成其他目录文件
#bases:
#  - ../rbac

#CM 注入
configMapGenerator:
  - files:
      - nginx.conf
    name: manager-config

#修改镜像
#images:
#  - name: controller
#    newName: docker.io/alanzy/aloysnginx
#    newTag: "1.0"
#
#patchesStrategicMerge:
#  - deploy.yaml