apiVersion: zy.tech/v1
kind: Aloys
metadata:
  name: aloys-sample
spec:
  # TODO(user): Add fields here
  deployment:
    replicas: 1
    containers:
      #      想了一下，还是添加一个名字，svc 暴露的时候添加需要暴露的container 名字比较好理解
      - name: aloysnginx
        image: docker.io/alanzy/aloysnginx:1.0
        port: 8080
        mountPath: /nginx/conf/nginx.conf
        limits:
          cpu: 50m
          memory: 128Mi
        request:
          cpu: 20m
          memory: 64Mi
      - name: nginx
        image: nginx
        port: 80
        limits:
          cpu: 50m
          memory: 128Mi
        request:
          cpu: 20m
          memory: 64Mi
  service:
    enable: true
    #设置需要暴露的容器端口,写死了就让暴露一个
    name: aloysnginx
  ingress:
    enable: true
    host: zy.aloys.tech
  configMap:
    - name: aloysnginx
      cmDate: |
        #user  nobody;
        worker_processes  1;

        #error_log  logs/error.log;
        #error_log  logs/error.log  notice;
        #error_log  logs/error.log  info;

        #pid        logs/nginx.pid;


        events {
            worker_connections  1024;
        }


        http {
            include       mime.types;
            default_type  application/octet-stream;

            #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
            #                  '$status $body_bytes_sent "$http_referer" '
            #                  '"$http_user_agent" "$http_x_forwarded_for"';

            #access_log  logs/access.log  main;

            sendfile        on;
            #tcp_nopush     on;

            #keepalive_timeout  0;
            keepalive_timeout  65;

            #gzip  on;

            server {
                listen       8080;
                server_name  localhost;

                #charset koi8-r;

                #access_log  logs/host.access.log  main;

                location / {
                    root   html;
                    index  index.html index.htm;
                }

                #error_page  404              /404.html;

                # redirect server error pages to the static page /50x.html
                #
                error_page   500 502 503 504  /50x.html;
                location = /50x.html {
                    root   html;
                }

                # proxy the PHP scripts to Apache listening on 127.0.0.1:80
                #
                #location ~ \.php$ {
                #    proxy_pass   http://127.0.0.1;
                #}

                # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
                #
                #location ~ \.php$ {
                #    root           html;
                #    fastcgi_pass   127.0.0.1:9000;
                #    fastcgi_index  index.php;
                #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
                #    include        fastcgi_params;
                #}

                # deny access to .htaccess files, if Apache's document root
                # concurs with nginx's one
                #
                #location ~ /\.ht {
                #    deny  all;
                #}
            }


            # another virtual host using mix of IP-, name-, and port-based configuration
            #
            #server {
            #    listen       8000;
            #    listen       somename:8080;
            #    server_name  somename  alias  another.alias;

            #    location / {
            #        root   html;
            #        index  index.html index.htm;
            #    }
            #}


            # HTTPS server
            #
            #server {
            #    listen       443 ssl;
            #    server_name  localhost;

            #    ssl_certificate      cert.pem;
            #    ssl_certificate_key  cert.key;

            #    ssl_session_cache    shared:SSL:1m;
            #    ssl_session_timeout  5m;

            #    ssl_ciphers  HIGH:!aNULL:!MD5;
            #    ssl_prefer_server_ciphers  on;

            #    location / {
            #        root   html;
            #        index  index.html index.htm;
            #    }
            #}

        }