# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
# WARNING: Targets CertManager v1.0. Check https://cert-manager.io/docs/installation/upgrading/ for breaking changes.
#cert-manager是一个原生的生成证书的 controller
#这个配置文件的整体作用是申请一张证书，存放在名称为webhook-server-cert 的secret里
#这是cert-manager的配置权限
apiVersion: cert-manager.io/v1
#Issuer 权限范围
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: system
spec:
  selfSigned: { }
---
#这个是申请证书的配置文件，我们可以部署这个文件，将证书保存到一个 secret中
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert  # this name should match the one appeared in kustomizeconfig.yaml
  namespace: system
spec:
  # $(SERVICE_NAME) and $(SERVICE_NAMESPACE) will be substituted by kustomize
  dnsNames:
    - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
    - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
  #制定 Issuer 信息
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert  #生成的证书保持在这里# this secret will not be prefixed, since it's not managed by kustomize