bases:
  - ../default

patches:
  - patch: |
      - op: "remove"
        path: "/spec/dnsNames"
    target:
      kind: Certificate
  - patch: |
      - op: "add"
        path: "/spec/ipAddresses"
        # value 设置的ip本机地址，要保证k8s能连接到,其实就是 webhook 在本地启动，连接到本机
        value: ["192.168.1.108"]
    target:
      kind: Certificate
  - patch: |
      - op: "add"
        path: "/webhooks/0/clientConfig/url"
        #https://192.168.1.108:9443/mutate-aloys-tech-v1-zy"
        #这也要修改，后面的修为为自己的 GVK mutate -GV（GV 之间用-连接 ）-K
        #  GroupVersion = schema.GroupVersion{Group: "zy.tech", Version: "v1"})
        value: "https://192.168.1.108:9443/mutate-zy-tech-v1-aloys"
    target:
      kind: MutatingWebhookConfiguration
  - patch: |
      - op: "add"
        path: "/webhooks/0/clientConfig/url"
        #别忘记这个也要修改
        value: "https://192.168.1.108:9443/validate-zy-tech-v1-aloys"
    target:
      kind: ValidatingWebhookConfiguration
  - patch: |
      - op: "remove"
        path: "/webhooks/0/clientConfig/service"
    target:
      kind: MutatingWebhookConfiguration
  - patch: |
      - op: "remove"
        path: "/webhooks/0/clientConfig/service"
    target:
      kind: ValidatingWebhookConfiguration